export const FETCH_JOKES = 'FETCH_JOKES';
export const FETCH_JOKES_REQUEST = 'FETCH_JOKES_REQUEST';
export const FETCH_JOKES_SUCCESS = 'FETCH_JOKES_SUCCESS';
export const FETCH_JOKES_FAILURE = 'FETCH_JOKES_FAILURE';

export const CREATE_JOKES = 'CREATE_JOKES';
export const CREATE_JOKES_REQUEST = 'CREATE_JOKES_REQUEST';
export const CREATE_JOKES_SUCCESS = 'CREATE_JOKES_SUCCESS';
export const CREATE_JOKES_FAILURE = 'CREATE_JOKES_FAILURE';

export const UPDATE_JOKES = 'UPDATE_JOKES';
export const UPDATE_JOKES_REQUEST = 'UPDATE_JOKES_REQUEST';
export const UPDATE_JOKES_SUCCESS = 'UPDATE_JOKES_SUCCESS';
export const UPDATE_JOKES_FAILURE = 'UPDATE_JOKES_FAILURE';

export const DELETE_JOKES = 'DELETE_JOKES';
export const DELETE_JOKES_REQUEST = 'DELETE_JOKES_REQUEST';
export const DELETE_JOKES_SUCCESS = 'DELETE_JOKES_SUCCESS';
export const DELETE_JOKES_FAILURE = 'DELETE_JOKES_FAILURE';
